### ISSUE TITLE
Multiples path for template folder.

### ISSUE THREAD

**Issue by Apkahym** [Wolf-Code/Template-Generator#1]
I think is a great update that this allow to have a global template folder and local/project templates.
Some times i need initialize a project with something configs files or folder structures and for this i use global template. But for each project i need different  templates and i create it, change the folder template path and loose access to global templates options.

i think that a good options for this are to use to configurations:
- base template path: common for all project and in a default path (vscode folder for example, with option to change it)
```
"templates.defaultPath":"/path/to/global/and/commons/templates"
```
- custom template paths: an array with absolute paths
```
"templates.paths": [
   "/path/to/languajes/templates",
   "/path/to/local/templates",
   "/path/to/shared/templates",
]
```

> At this moment i don't have time to make a change and create the PR. When  will can, i do!!

**Comment by Wolf-Code** [comment]
Great addition! I'll see if I can find some time to add this in the coming days :) Thanks!

**Comment by Wolf-Code** [comment]
@Apkahym Actually, I just went ahead and added it right now. New version is publishing as we speak! Thanks again for the suggestion!

**Comment by Apkahym** [comment]
First at all, thanks for interest on my issue, i tested it and work perfectly
In second place, i think i not explain me correctly about my idea.

actually `templates.path` permit a single path in the local workspace, we be name "root template".

And recently added `templates.additionalPaths` permit a multiple paths in the local workspace too, i think this paths can be name "secondary templates"

When i propoused this issue i thinking in something like a "global template", that permit add multiples or simple path reading the root file system, like `$HOME/.vscode/templates`, with this options we can create templates for all project independently if the proyecto has root template or secondary templates.

what think you about that?
